== The Adopted Stabber
============
Hello there! This is a W.I.P...!
We're basically recreating the concept of The Hidden: Source but a bit differently...
Recreating it will be fun! The mechanics aren't hard to get down pat!

It will be like the original, on the Source Engine, but reduxed and refined to be newer with a differences such as game play mechanics, audio-cues, etc!
============

== NEEDS
[width="100%",cols="1s,5",frame="none",options="header"]
|====================
| Job Title... | Reasonning on why we need them...
| Idealists | We need people who are creative!!! We all have a little spunk, but some more than others!
| Voice Actors | We will need some voluntary voice acting if we decide to place a voice-play radial menu!
| Map Creators | We of course need more than just what we got! Creativity is a hard thing to come by!
| Model Creators | Same as before... We of course need more than just what we got! Creativity is a hard thing to come by!
| Artists | Same as before but slightly different... We need them for *_concept art_* and other such!
|====================

pass:q[<form action="https://fogpay.com/payment_api/payment" method="POST" style="text-align:center;"><input type="hidden" name="trans_type" value="payment"><input type="hidden" name="account_username" value="AltEDU"><span>$</span><input name="amount" type="number" min="1.0" value="5.0" style="width: 7.5%;text-align:center">USD <input type="submit" value="Perform Donation"></form>]